services:
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name nats --http_port 8222 --js"
    networks: ["nats"]

  nats_stream_creator:
    image: synadia/nats-server:nightly
    depends_on:
      - nats
    entrypoint: [
      "sh", "-c",
      "until nats --server=nats:4222 stream create payments --subjects 'payment.process' --storage memory --replicas 1 --retention=limits --discard=old --max-msgs 1000000 --max-msgs-per-subject 100000 --max-bytes 4294967296 --max-age 1d --max-msg-size 10485760 --dupe-window 2m --allow-rollup --no-deny-delete --no-deny-purge; do sleep 1; done"
    ]
    networks: [ "nats" ]

networks:
  nats:
    name: nats

